<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTioye3d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTioye3d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTioye3d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTioye3d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTioye3d\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tioye3d',
    'container.build_id' => '213d3d2f',
    'container.build_time' => 1612135189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTioye3d');
