<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFlJP6LM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFlJP6LM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFlJP6LM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFlJP6LM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFlJP6LM\App_KernelDevDebugContainer([
    'container.build_hash' => 'FlJP6LM',
    'container.build_id' => 'e7ccd81b',
    'container.build_time' => 1610316788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFlJP6LM');
